### ISSUE TITLE
Add tests to django example app

### ISSUE THREAD

**Issue by andersonresende** [vintasoftware/django-react-boilerplate#54]

**Comment by aericson** [comment]
Add some example views and test them.

**Comment by hansdereber** [comment]
Prezadxs,

I would like to contribute to this project and have found this issue to be interesting task.

I have created a pull request #434 where the example app is extended with models, views and tests (!). The added views follow the offical Django 2.2 tutorial: [https://docs.djangoproject.com/en/2.2/intro/tutorial01/](https://docs.djangoproject.com/en/2.2/intro/tutorial01/).

As this issue is already a little old, I hope that the change is still relevant.

Best regards e abraços

**Comment by hansdereber** [comment]
Unfortunatly the circleci build is erroring out with:

> FileNotFoundError: [Errno 2] No such file or directory: '/home/circleci/django-react-boilerplate/testproject/backend/../webpack-stats.json'

I could not locate the error in the ci build. Any help?

**Comment by jhgv** [comment]
Hi @hansdereber,

It doesn't seem to be related to your PR. I will take a look and get back to you with more information as soon as possible.

**Comment by hansdereber** [comment]
@jhgv did you find any clous why the ci build is broken?

**Comment by jhgv** [comment]
@hansdereber
Try replacing **STATIC_ROOT**, **STATIC_URL**, **MEDIA_ROOT**, and **MEDIA_URL** in settings.test with:

```python
STATIC_ROOT = "staticfiles"
STATIC_URL = "/static/"

MEDIA_ROOT = "mediafiles"
MEDIA_URL = "/media/"
```

**Comment by hansdereber** [comment]
The tests were failing because they depended on the webpack build. So I needed to change the circle ci config.yaml file. I have reordered the config.yaml file. It now builds and tests the frontend first, then it builds and tests the backend. Now the ci build is green with all 10 tests passing.

**Comment by fjsj** [comment]
Django example app is minimal now, so closing this.
